#!/Users/tabishshahmohsin/Desktop/GitHub/cs50ai_harvard/lecture_1/knights/bin/python3.13
# -*- coding: utf-8 -*-
import re
import sys
from check50.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
